// Generated by CoffeeScript 1.7.1
(function() {
  Meteor.publish('adminCollection', function(collection) {
    if (Roles.userIsInRole(this.userId, ['admin'])) {
      return global[collection].find();
    } else {
      return this.ready();
    }
  });

  Meteor.publish('adminAuxCollections', function(collection) {
    var subscriptions;
    if (Roles.userIsInRole(this.userId, ['admin'])) {
      if (typeof AdminConfig !== 'undefined' && typeof AdminConfig.collections[collection].auxCollections === 'object') {
        subscriptions = [];
        _.each(AdminConfig.collections[collection].auxCollections, function(collection) {
          return subscriptions.push(global[collection].find());
        });
        return subscriptions;
      } else {
        return this.ready();
      }
    } else {
      return this.ready();
    }
  });

  Meteor.publish('adminAllCollections', function() {
    var subscriptions;
    if (Roles.userIsInRole(this.userId, ['admin'])) {
      if (typeof AdminConfig !== 'undefined' && typeof AdminConfig.collections === 'object') {
        subscriptions = [];
        _.map(AdminConfig.collections, function(obj, key) {
          console.log(key, obj);
          subscriptions.push(global[key].find());
          return console.log("pub ok", key);
        });
        return subscriptions;
      }
    } else {
      return this.ready();
    }
  });

  Meteor.publish('adminUsers', function() {
    if (Roles.userIsInRole(this.userId, ['admin'])) {
      return Meteor.users.find();
    } else {
      return this.ready();
    }
  });

  Meteor.publish('adminUser', function() {
    return Meteor.users.find(this.userId);
  });

  Meteor.publish(null, function() {
    return Meteor.roles.find({});
  });

}).call(this);

//# sourceMappingURL=publish.map
