// Generated by CoffeeScript 1.7.1
(function() {
  Router.onBeforeAction(AdminDashboard.checkAdmin, {
    only: AdminDashboard.adminRoutes
  });

  Router.onBeforeAction(AdminDashboard.clearAlerts, {
    only: AdminDashboard.adminRoutes
  });

  Router.map(function() {
    this.route("adminDashboard", {
      path: "/admin",
      template: "AdminDashboard",
      layoutTemplate: "AdminLayout",
      waitOn: function() {
        return [Meteor.subscribe('adminUsers', Meteor.subscribe('adminAllCollections', Meteor.subscribe('adminUser')))];
      },
      action: function() {
        Session.set('admin_title', 'Dashboard');
        Session.set('admin_collection', '');
        Session.set('admin_collection_page', '');
        return this.render();
      }
    });
    this.route("adminDashboardUsersNew", {
      path: "/admin/Users/new",
      template: "AdminDashboardUsersNew",
      layoutTemplate: "AdminLayout",
      waitOn: function() {
        return [Meteor.subscribe('adminUsers', Meteor.subscribe('adminUser'))];
      },
      action: function() {
        Session.set('admin_title', 'Users');
        Session.set('admin_subtitle', 'Create new user');
        Session.set('admin_collection_page', 'New');
        Session.set('admin_collection', 'Users');
        return this.render();
      }
    });
    this.route("adminDashboardUsersView", {
      path: "/admin/Users/",
      template: "AdminDashboardUsersView",
      layoutTemplate: "AdminLayout",
      waitOn: function() {
        return [Meteor.subscribe('adminUsers', Meteor.subscribe('adminUser'))];
      },
      data: function() {
        return {
          users: Meteor.users.find({}, {
            sort: {
              createdAt: -1
            }
          }).fetch()
        };
      },
      action: function() {
        Session.set('admin_title', 'Users');
        Session.set('admin_subtitle', 'View users');
        Session.set('admin_collection_page', '');
        Session.set('admin_collection', 'Users');
        return this.render();
      }
    });
    this.route("adminDashboardUsersEdit", {
      path: "/admin/Users/:_id/edit",
      template: "AdminDashboardUsersEdit",
      layoutTemplate: "AdminLayout",
      waitOn: function() {
        return [Meteor.subscribe('adminUsers', Meteor.subscribe('adminUser'))];
      },
      data: function() {
        return {
          user: Meteor.users.find({
            _id: this.params._id
          }).fetch(),
          roles: Roles.getRolesForUser(this.params._id),
          otherRoles: _.difference(_.map(Meteor.roles.find().fetch(), function(role) {
            return role.name;
          }), Roles.getRolesForUser(this.params._id))
        };
      },
      action: function() {
        Session.set('admin_title', 'Users');
        Session.set('admin_subtitle', 'Edit user ' + this.params._id);
        Session.set('admin_collection_page', 'edit');
        Session.set('admin_collection', 'Users');
        Session.set('admin_id', this.params._id);
        Session.set('admin_doc', Meteor.users.findOne({
          _id: this.params._id
        }));
        return this.render();
      }
    });
    this.route("adminDashboardView", {
      path: "/admin/:collection/",
      template: "AdminDashboardView",
      layoutTemplate: "AdminLayout",
      waitOn: function() {
        return [Meteor.subscribe('adminCollection', this.params.collection), Meteor.subscribe('adminAuxCollections', this.params.collection), Meteor.subscribe('adminUsers'), Meteor.subscribe('adminUser')];
      },
      data: function() {
        return {
          documents: window[this.params.collection].find({}, {
            sort: {
              createdAt: -1
            }
          }).fetch()
        };
      },
      action: function() {
        Session.set('admin_title', AdminDashboard.collectionLabel(this.params.collection));
        Session.set('admin_subtitle', 'View ');
        Session.set('admin_collection_page', '');
        Session.set('admin_collection', this.params.collection.charAt(0).toUpperCase() + this.params.collection.slice(1));
        return this.render();
      }
    });
    this.route("adminDashboardNew", {
      path: "/admin/:collection/new",
      template: "AdminDashboardNew",
      layoutTemplate: "AdminLayout",
      waitOn: function() {
        return [Meteor.subscribe('adminAuxCollections', this.params.collection), Meteor.subscribe('adminUsers'), Meteor.subscribe('adminUser')];
      },
      action: function() {
        Session.set('admin_title', AdminDashboard.collectionLabel(this.params.collection));
        Session.set('admin_subtitle', 'Create new');
        Session.set('admin_collection_page', 'new');
        Session.set('admin_collection', this.params.collection.charAt(0).toUpperCase() + this.params.collection.slice(1));
        return this.render();
      }
    });
    return this.route("adminDashboardEdit", {
      path: "/admin/:collection/:_id/edit",
      template: "AdminDashboardEdit",
      layoutTemplate: "AdminLayout",
      waitOn: function() {
        return [Meteor.subscribe('adminCollection', this.params.collection), Meteor.subscribe('adminAuxCollections', this.params.collection), Meteor.subscribe('adminUsers'), Meteor.subscribe('adminUser')];
      },
      action: function() {
        Session.set('admin_title', AdminDashboard.collectionLabel(this.params.collection));
        Session.set('admin_subtitle', 'Edit ' + this.params._id);
        Session.set('admin_collection_page', 'edit');
        Session.set('admin_collection', this.params.collection.charAt(0).toUpperCase() + this.params.collection.slice(1));
        Session.set('admin_id', this.params._id);
        Session.set('admin_doc', window[this.params.collection].findOne({
          _id: this.params._id
        }));
        return this.render();
      }
    });
  });

}).call(this);

//# sourceMappingURL=router.map
